"""Storage and Connections configuration view for MasCloner console."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import streamlit as st

try:
    from app.ui.api_client import APIClient
    from app.ui.components.theme import (
        format_bytes,
        format_iso_time,
        render_hero_bar,
    )
except ImportError:
    from api_client import APIClient
    from components.theme import (
        format_bytes,
        format_iso_time,
        render_hero_bar,
    )


def get_api() -> APIClient:
    return APIClient()


api = get_api()

st.title("🔗 Storage & Connections")
render_hero_bar(api)

# Fetch current configuration
paths = api.get_sync_paths() or {}
gdrive_src = paths.get("gdrive_src") or "/"
nc_dest_path = paths.get("nc_dest_path") or "/"

# 1. Global Endpoint Verification Action
header_col1, header_col2 = st.columns([3, 1])
with header_col1:
    st.subheader("Active Endpoint Status")
    st.caption("Inspect and verify connectivity to the Google Drive source and Nextcloud destination")

with header_col2:
    if st.button("⚡ Verify Both Endpoints", help="Test both Google Drive API and Nextcloud WebDAV connectivity", use_container_width=True):
        with st.spinner("Probing endpoints..."):
            gd_res = api.test_google_drive_connection() or {}
            nc_res = api.test_nextcloud() or {}
            st.session_state.route_verification = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "gdrive_ok": gd_res.get("success", False),
                "gdrive_msg": gd_res.get("message", "Unknown status"),
                "nc_ok": nc_res.get("success", False),
                "nc_msg": nc_res.get("message", "Unknown status"),
            }
            st.rerun()

verification = st.session_state.get("route_verification")
if verification:
    st.caption(f"Last verified: {format_iso_time(verification['timestamp'], include_relative=True)}")

st.divider()

# 2. Side-by-Side Connection Cards
col_gd, col_nc = st.columns(2)

# --- Google Drive Card ---
with col_gd.container(border=True):
    st.markdown("### 📁 Google Drive Source")
    st.markdown(f"**Target Remote**: `gdrive`")
    st.markdown(f"**Source Root Path**: `{gdrive_src}`")

    gd_status = api.get_google_drive_status() or {}
    is_gd_connected = gd_status.get("connected", False)

    if verification:
        if verification["gdrive_ok"]:
            st.success(f"🟢 {verification['gdrive_msg']}")
        else:
            st.error(f"🔴 {verification['gdrive_msg']}")
    else:
        if is_gd_connected:
            st.success("🟢 Connected & Authenticated")
        else:
            st.error("🔴 Disconnected / Missing Token")

    if st.button("🔍 Test Google Drive Connection", key="test_gd_btn", use_container_width=True):
        with st.spinner("Testing Google Drive..."):
            res = api.test_google_drive_connection() or {}
            if res.get("success"):
                st.success(f"Connection test passed: {res.get('message', 'OK')}")
            else:
                st.error(f"Connection failed: {res.get('message', 'Failed')}")

    # Re-authentication Form
    with st.expander("🔑 Update OAuth Token / Re-authenticate"):
        with st.form("gd_token_form"):
            st.caption("Paste the JSON or token string generated by rclone authorize 'drive'")
            token_input = st.text_area("OAuth Token JSON", height=100)
            scope_input = st.pills("OAuth Scope", options=["drive.readonly", "drive"], default="drive.readonly")
            submit_token = st.form_submit_button("Save & Authorize Token")

            if submit_token:
                if not token_input.strip():
                    st.error("Token cannot be empty")
                else:
                    save_res = api.configure_google_drive_oauth(token=token_input.strip(), scope=scope_input)
                    if save_res and save_res.get("success"):
                        st.success("Google Drive authorized successfully!")
                        st.rerun()
                    else:
                        st.error(f"Failed to authorize: {save_res.get('message') if save_res else 'Error'}")

    # Custom OAuth Client Credentials Form
    with st.expander("⚙️ Custom OAuth Client Credentials (Optional)"):
        oauth_cfg = api.get_google_drive_oauth_config() or {}
        has_custom = oauth_cfg.get("has_custom_oauth", False)
        if has_custom:
            st.info("Using custom Google Drive OAuth Client credentials")
        else:
            st.caption("Using default embedded credentials")

        with st.form("custom_oauth_form"):
            client_id = st.text_input("Client ID", value=oauth_cfg.get("client_id") or "")
            client_secret = st.text_input("Client Secret", type="password", value="" if not has_custom else "********")
            save_custom = st.form_submit_button("Save Custom Credentials")

            if save_custom:
                if client_id and client_secret and client_secret != "********":
                    c_res = api.save_google_drive_oauth_config(client_id.strip(), client_secret.strip())
                    if c_res and c_res.get("success"):
                        st.success("Custom OAuth credentials saved!")
                        st.rerun()
                    else:
                        st.error("Failed to save credentials")
                else:
                    st.warning("Please specify both client ID and client secret")


# --- Nextcloud WebDAV Card ---
with col_nc.container(border=True):
    st.markdown("### ☁️ Nextcloud Destination")
    st.markdown(f"**Target Remote**: `ncwebdav`")
    st.markdown(f"**Destination Path**: `{nc_dest_path}`")

    nc_status = api.get_nextcloud_status() or {}
    is_nc_configured = nc_status.get("configured", False)

    if verification:
        if verification["nc_ok"]:
            st.success(f"🟢 {verification['nc_msg']}")
        else:
            st.error(f"🔴 {verification['nc_msg']}")
    else:
        if is_nc_configured:
            st.success("🟢 WebDAV Configured & Ready")
        else:
            st.error("🔴 Nextcloud WebDAV Not Configured")

    if st.button("🔍 Test Nextcloud Connection", key="test_nc_btn", use_container_width=True):
        with st.spinner("Testing Nextcloud WebDAV..."):
            res = api.test_nextcloud() or {}
            if res.get("success"):
                st.success(f"WebDAV test passed: {res.get('message', 'OK')}")
            else:
                st.error(f"WebDAV test failed: {res.get('message', 'Failed')}")

    # WebDAV Configuration Form
    with st.expander("⚙️ Configure Nextcloud WebDAV Credentials"):
        with st.form("nc_cred_form"):
            webdav_url = st.text_input("Nextcloud WebDAV URL", value=nc_status.get("url") or "https://nextcloud.example.com/remote.php/dav/files/user/")
            webdav_user = st.text_input("Username", value=nc_status.get("user") or "")
            webdav_pass = st.text_input("App Password", type="password")
            submit_nc = st.form_submit_button("Save & Test WebDAV Credentials")

            if submit_nc:
                if not webdav_url.strip() or not webdav_user.strip() or not webdav_pass.strip():
                    st.error("All WebDAV fields are required")
                else:
                    nc_save_res = api.test_nextcloud_webdav(
                        url=webdav_url.strip(),
                        user=webdav_user.strip(),
                        password=webdav_pass.strip(),
                    )
                    if nc_save_res and nc_save_res.get("success"):
                        st.success("Nextcloud credentials saved and verified!")
                        st.rerun()
                    else:
                        err = nc_save_res.get("message") if nc_save_res else "Connection failed"
                        st.error(f"Failed to connect to Nextcloud: {err}")

st.divider()

# 3. Advanced Mode: Modify Sync Paths & Folder Browser (Collapsed by default - Q5=A)
with st.expander("🛠️ Advanced: Modify Sync Paths & Folder Browser", expanded=False):
    st.warning("⚠️ **Notice**: MasCloner is configured for continuous synchronization between two fixed folders. Only modify these values if you are deliberately altering your sync targets.")

    with st.form("modify_paths_form"):
        new_gdrive_src = st.text_input("Google Drive Source Path", value=gdrive_src, help="Root path in Google Drive to read from, e.g. /CompanyFiles or /")
        new_nc_dest = st.text_input("Nextcloud Destination Path", value=nc_dest_path, help="Target folder in Nextcloud to write to, e.g. /Backups/CompanyFiles or /")
        save_paths_btn = st.form_submit_button("💾 Save New Paths Directly to SQLite")

        if save_paths_btn:
            # Q8=B: Save directly to SQLite
            upd_res = api.update_sync_paths({
                "gdrive_src": new_gdrive_src.strip() or "/",
                "nc_dest_path": new_nc_dest.strip() or "/",
            })
            if upd_res and upd_res.get("success"):
                st.success("Sync paths successfully updated in SQLite database!")
                st.rerun()
            else:
                msg = upd_res.get("message") if upd_res else "Failed to update paths"
                st.error(f"Error: {msg}")

    # Optional Remote Folder Exploration helper
    st.markdown("##### 📂 Optional Remote Folder Inspection")
    browse_col1, browse_col2 = st.columns(2)
    with browse_col1:
        if st.button("Browse Google Drive Folders", key="browse_gd"):
            res = api.browse_folders("gdrive", path=gdrive_src) or {}
            folders = res.get("folders", [])
            if folders:
                st.write(f"Folders found in `{gdrive_src}`:")
                for f in folders[:10]:
                    st.code(f)
            else:
                st.caption(f"No subfolders found or unable to browse `{gdrive_src}`.")
    with browse_col2:
        if st.button("Browse Nextcloud Folders", key="browse_nc"):
            res = api.browse_folders("ncwebdav", path=nc_dest_path) or {}
            folders = res.get("folders", [])
            if folders:
                st.write(f"Folders found in `{nc_dest_path}`:")
                for f in folders[:10]:
                    st.code(f)
            else:
                st.caption(f"No subfolders found or unable to browse `{nc_dest_path}`.")
