"""Data models for backup-first migration and rollback workflow (ADR 0001, ADR 0003, Issue #14)."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class MigrationMode(str, Enum):
    """Execution mode for migration."""
    CHECK = "check"
    DRY_RUN = "dry-run"
    APPLY = "apply"
    ROLLBACK = "rollback"


class MigrationStep(str, Enum):
    """Checkpointable steps in the migration pipeline."""
    PREFLIGHT = "preflight"
    QUIESCE = "quiesce"
    BACKUP = "backup"
    INVENTORY = "inventory"
    SCHEMA_MIGRATE = "schema_migrate"
    IMPORT_CONFIG = "import_config"
    VALIDATE_ENDPOINTS = "validate_endpoints"
    PROMOTE_ENDPOINTS = "promote_endpoints"
    SMOKE_TEST = "smoke_test"
    ENABLE_RETENTION = "enable_retention"
    COMPLETED = "completed"


class PreflightCheckResult(BaseModel):
    """Health and prerequisite checks before migration."""
    model_config = ConfigDict(extra="ignore")

    topology_ok: bool = True
    free_space_mb: float = 0.0
    free_space_ok: bool = True
    permissions_ok: bool = True
    database_integrity_ok: bool = True
    no_active_runs_ok: bool = True
    details: Dict[str, Any] = Field(default_factory=dict)
    errors: List[str] = Field(default_factory=list)

    @property
    def is_healthy(self) -> bool:
        return (
            self.topology_ok
            and self.free_space_ok
            and self.permissions_ok
            and self.database_integrity_ok
            and self.no_active_runs_ok
            and len(self.errors) == 0
        )


class RecoveryBundleInfo(BaseModel):
    """Metadata describing a verified pre-migration recovery bundle."""
    model_config = ConfigDict(extra="ignore")

    bundle_dir: str
    database_backup_path: str
    env_backup_path: str
    rclone_backup_path: Optional[str] = None
    metadata_path: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    verified: bool = False
    source_hashes: Dict[str, str] = Field(default_factory=dict)


class MigrationReport(BaseModel):
    """Report generated by migration or rollback operation."""
    model_config = ConfigDict(extra="ignore")

    mode: MigrationMode
    success: bool = False
    current_step: MigrationStep = MigrationStep.PREFLIGHT
    preflight: Optional[PreflightCheckResult] = None
    recovery_bundle: Optional[RecoveryBundleInfo] = None
    migrated_settings: Dict[str, Any] = Field(default_factory=dict)
    endpoints_validated: List[str] = Field(default_factory=list)
    resumable_boundary: Optional[str] = None
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    finished_at: Optional[datetime] = None
    error: Optional[str] = None
    warnings: List[str] = Field(default_factory=list)

    @property
    def duration_seconds(self) -> float:
        end = self.finished_at or datetime.now(timezone.utc)
        return max(0.0, (end - self.started_at).total_seconds())
